### PR TITLE
Add UI Tests

### PR DESCRIPTION
**Pull request by Jonahss**
Everybody loves tests!

I wrote these to demo the new XCUITest framework. What do you think?

### CODE REVIEW

**Comment by KacheFlowe** [comment]
Hey man, if you can resolve any conflicts in the app I'm down to merge this.

**Comment by Jonahss** [comment]
oh coolio. I'll see what I can do

**Comment by Jonahss** [comment]
@KacheFlowe Conflicts resolved.

**Comment by KacheFlowe** [comment]
Word, thanks @Jonahss

**Comment by swiftcodex** [comment]
Thanks @Jonahss! 👍

**Comment by Jonahss** [comment]
My pleasure ^.^

**Comment by dag08** [comment]
Hi,

I have a little problem with the title and artist. Some title or artist have äöüß etc. in his names. This appears not correct. What could I do to solve it?

**Comment by swiftcodex** [comment]
Hi dag08, sorry you are having trouble. **Please note that Pull requests are not for technical support**. However, as a friendly hello- It sounds like your stations maybe sending some non-english characters or bad metadata. You can update the way you the app processes the metadata strings in the metadata named method in the NowPlayingViewController.

**Comment by dag08** [comment]
Hi @swiftcodex, thank you for a very quick answer!
I'm newbie in Swift where could I get support for my issue? I had tried to fix it but my experience is to low for it. 

Thank you!!!!

**Comment by swiftcodex** [comment]
Hi @dag08, welcome to Swift! I'd highly recommend you find a developer or mentor in your area to help. As per the FAQ: we have full time jobs and can not provide any free support or help anyone learn to program. Best of luck!

**Pull request merged**
