### PR TITLE
Fix Master branch asking for conversion to Swift 3 #37

### PR DESCRIPTION
**Pull request by RealBug**
Hi

Its a little PR for upgrade test's target to Swift 3 => No more popup :) 

RealBug

### CODE REVIEW

**Comment by swiftcodex** [comment]
Thanks!

**Comment by ShanghaiTimes** [comment]
It's still running Deployment Target 8.0 - Badly needs updating to 10.1, Lots of things depreciated now such as MPMoviePlayerController, UIAlert, openURL etc... all depreciated back in DP 9.0

**Comment by swiftcodex** [comment]
@ShanghaiTimes you can make a 10.1 branch. Over 70% of the apps in the appstore using this code are in non-english speaking countries using older versions of iOS. Forcing everyone to upgrade to 10.1 is not very nice.

**Comment by swiftcodex** [comment]
@ShanghaiTimes - There are two branches using AVPlayer instead of MPMoviePlayer if you need hints...

**Pull request merged**
