### PR TITLE
Add share button

### PR DESCRIPTION
**Pull request by SuperChloe**
Add button to the Now Playing screen to allow sharing of the current song & station via UIActivityViewController

### CODE REVIEW

**Comment by swiftcodex** [comment]
Thanks Chloe! I will take a look at this over the weekend.

**Comment by swiftcodex** [comment]
Thanks Chloe, I have added your code and thanked you in the readme. (BTW, I updated the share icon to be the iOS 9 share icon, I hope you don't mind).
screen shot 2016-02-24 at 10 09 43 am
screen shot 2016-02-24 at 10 10 00 am
screen shot 2016-02-24 at 10 05 08 am

**Comment by swiftcodex** [comment]
Share works great. Dig that you put it in the segue section. Thanks again.

**Comment by SuperChloe** [comment]
Thanks!

Glad you liked it! :)

- Chloe

**Pull request closed without merging**
