### PR TITLE
Handoff branch

### PR DESCRIPTION
**Pull request by GraemeHarrison**
Added handoff functionality. Web browser with google search for current song/station pops up on toolbar of user's mac.

### CODE REVIEW

**Comment by swiftcodex** [comment]
Thanks Graeme, I'll try to take a look at this over the weekend. Thanks for your contribution and patience!

**Comment by KacheFlowe** [comment]
Hi Graeme, is there anyway you can resolve the conflicts?

**Comment by KacheFlowe** [comment]
Hey @GraemeHarrison there seem to be a lot of issues with the code even after the conflicts are resolved, anyway you could take a look at that? Hoping to hear from you.

**Comment by GraemeHarrison** [comment]
Hi @KacheFlowe ,
Thanks for checking out my contribution! Sorry I couldn’t get back to you yesterday, I’ve been swamped with work this week and haven't had chance to review the code. 
Before I submitted the branch everything worked fine on my end. What kinds of issues are you running into? I’ll try to find some time to look through it this week and I’ll get back to you as soon as possible.

**Comment by swiftcodex** [comment]
Note: I've been having problems with Handoff ever since I upgraded to El Capitan. So, I will have to trust that it works based on your testing.

**Comment by GraemeHarrison** [comment]
I initially couldn't get Handoff to work either. In order to get it up and running with my mac and iPhone I had to follow the steps outlined in this article http://www.igeeksblog.com/handoff-and-airdrop-not-working/ 
Mainly: 
1) Delete /Library/Preferences/com.apple.Bluetooth.plist 
2) Sign out of iCloud from both the devices. 
3) Sign back in to iCloud on iPhone or iPad and also on your Mac.
I hope this helps!

**Comment by swiftcodex** [comment]
Thanks Graeme, I was able to resolve the conflicts, but, only with some git tricks. It says the commit is from me, however, I gave you credit in the git commit message. Hope that is okay. Thanks! 

screen shot 2016-03-27 at 11 47 18 am

**Pull request closed without merging**
