### PR TITLE
VolumeFix

### PR DESCRIPTION
**Pull request by skumar2998**

### CODE REVIEW

**Comment by swiftcodex** [comment]
Hi there,
There's a few issues: 

(1) Too many unrelated changes in one PR. One change or feature per PR, please. i.e. "Fix AutoLayout" and "Volume Slider" should be separate Pull Requests.
(2) Modifying outside Libraries (Spring), that will be overwritten
(3) Modifying code signature changes from the original author
(4) MAIN ISSUE: Your code has several errors and warnings with the current, non-beta version of Xcode. Code with errors should not be committed to Master. A rule of thumb is if the code does not compile, it should not be committed until those errors are fixed.

As this PR includes (A) far-reaching changes to unrelated files that are not part of the main described feature in the PR and (B) user-introduced errors from modifying outside libraries, it will be closed. You are welcome to resubmit under those guidelines. Thank you!

**Comment by swiftcodex** [comment]
Adium: If you would like to work on an Xcode 8 branch, please start with the "AVPlayer" branch. Swift 2.3 code should not be used on the current master. Thank you

**Comment by easyjam** [comment]
Hi Matthew,
Is using AvPlayer branch with Xcode and swift 3 the recommended way going
forward for this project?  Sorry if this is not the right place to ask
this. Thank You

**Comment by swiftcodex** [comment]
Yes, the current master will be depreciated when Xcode 8 is officially released. I have not had a chance to work on the Xcode 8 version. So, you are welcome to work on it if you would like.

**Comment by easyjam** [comment]
Ok, thank you for the quick reply and the heads up much appreciated.

**Pull request closed without merging**
