### PR TITLE
Xcode 9 / Swift 4

### PR DESCRIPTION
**Pull request by fethica**
This is an update to Swift 4 / Xcode 9 (and support for the iPhone X new layout), please note that it's using the deprecated MediaPlayer framework, it will be converted to the AVKit soon!

Thanks :)

### CODE REVIEW

**Comment by swiftcodex** [comment]
@fethica You can merge your own pull requests if you'd like. No need to ask me!

**Comment by fethica** [comment]
@swiftcodex ok! Thanks 👍

**Comment by swiftcodex** [comment]
Feel free to update the Readme w/ the Xcode 9 info and add your name to the credits- You deserve credit!

**Comment by fethica** [comment]
Done!

**Pull request merged**
