### PR TITLE
Fix Array index out of range issue

### PR DESCRIPTION
**Pull request by fethica**

### CODE REVIEW

**Comment by KacheFlowe** [comment]
Could you elaborate as to why you feel this is necessary? I'm not sure if I completely understand your logic.

**Comment by swiftcodex** [comment]
Hi Fethica,
Thank you for submitting a PR. I agree with Basel that the logic you suggest will not affect the control flow and could lead to additional meta-data errors on many Icecasts. However, I have run into "Array out of range" warnings with streams with different meta-data formats. It is best to customize the meta-data parsing code to fit the radio stream formats you are including. Hopefully the stream provider will have documentation for you. However, I am very open to your suggestion if you could elaborate further, thanks much!

**Comment by fethica** [comment]
Sure ! 

I have crash error caused by "track.title = stringParts[1]" line.

"stringParts.count" is not a 0 based counter so "stringParts.count > 0" is true when "stringParts" has only one element and "stringParts[1]" (2nd element) will be out of rang and throws an error "Array index out of range", it is safer to use (stringParts.count > 1). Thanks!

**Comment by swiftcodex** [comment]
Hi Fethica,
To echo my collaborators, all Swift arrays are zero based. However, I agree with some of your logic. In the nature of fostering a positive and inclusive project, I will allow this merge. Thank you, sir!

**Comment by fethica** [comment]
Okay thank you!

Yes Swift array are 0 based, but the counter Array.count is not, for instance : 

let array = ["element"]
array.count // will return 1 not 0 
if array.count > 0 {
    let test = array[1] // will throw an error "Array out of range" you are trying to access the 2nd element 
}

To be safe : "if array.count > 1" is true when the array has more than 2 elements.

**Comment by swiftcodex** [comment]
Ahh, yes, I agree! You are correct. Apologies, I mis-interpreted your suggestion. Thank you very much for the clarification!

**Comment by fethica** [comment]
Welcome ! Thank you too for this great open source app :+1:

**Pull request merged**
