### PR TITLE
updates - avplayer - spotify

### PR DESCRIPTION
**Pull request by kusikusa**
Hi, thanks for sharing this, it was very useful to me.
I've made a couple of changes: switching to AVPlayer because MPMoviePlayerController is deprecated in IOS9 and adding Spotify as a cover API.

It's my first time contributing to anything,  I'm not entirely sure I'm doing it right.

Regards,
Xavier

### CODE REVIEW

**Comment by swiftcodex** [comment]
Thanks @kusikusa, I will take a look at this over the weekend. Switching to AVPlayer was on my roadmap, so, I appreciate you stepping up and helping out!

**Comment by swiftcodex** [comment]
Hi @kusikusa, thanks for this. This is a good attempt. Right now, there's a couple of issues preventing me from merging this to master without any changes: (1) it crashes within 1 minute of use in three tries on both the simulator and a 6s Plus. (2) functionality of now playing animation no longer works. 

If you'd like to fix and resubmit a PR that would be okay. Or, a better solution would be to break up the PR into separate PRs for different functionality (e.g. Spotify API, AVPlayer, etc). There's a lot here in a single PR request. Since it does not all work, it must be denied as a merge to master. Or, you are welcome to wait until I have some time to fix your code and I'll merge myself. Happy to help. Either one is fine, thanks again!

**Comment by kusikusa** [comment]
Hello @swiftcodex,
I'm sorry, I should have been more careful before submitting my code.
There's indeed a silent deallocation happening on the AVPlayerItem after a moment, I'll try to find a reliable way to fix it (probably by extending AVPLayerITem and remove the observer right before deallocation).
Bug number 2 should be easier to fix.
I'll take a look at it as soon as i can, and make separate PRs this time.

P.S. the radio streams seem to be down.

**Comment by kusikusa** [comment]
Hi again, I think I've fixed both issues, but I won't bother you again with a pull request - I don't really know what I'm doing anyway - but you can take a look at  the fixed code here it you wish:
https://github.com/kusikusa/Swift-Radio-Pro/tree/avplayer

I've finally kept the enum for the APIs, but removed Spotify because the tos don't allow the use of cover without putting a link back to Spotify on it. Too bad, because lastfm's data is a bit outdated.
Do whatever you please with it. I hope it will at least help you a bit to migrate to AVPlayer.

**Comment by swiftcodex** [comment]
@kusikusa your new AVPlayer code looks very nice and much improved! Would you like to make another PR, that way you will receive credit in the commit history? 

Regarding Spotify, I agree. Though, we can default the code to use LastFM and add a disclaimer that people will need to follow the Spotify TOS if they intend to use it in a production app. So, I would welcome a commit with that contribution as well. Thank you for the contribution and quick turnaround!

**Comment by swiftcodex** [comment]
@kusikusa and you are correct, I should probably update the example radio stations, a couple of them appear to be no longer streaming at those URLs

**Pull request closed without merging**
